workspace = { members = ["struct_bytes"] }
[package]
name = "rust-dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
struct_bytes = { version = "0.1.0", path = "struct_bytes" }
